import { useState, useEffect } from 'react';
import {
  Box,
  Flex,
  Heading,
  Text,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Badge,
  Spinner,
  useToast,
  HStack,
  Button,
  IconButton,
  Input,
  InputGroup,
  InputLeftElement,
  VStack
} from '@chakra-ui/react';
import { 
  Search, 
  Printer, 
  Download, 
  ShoppingBag,
  TrendingUp,
  Receipt
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import Layout from '../../components/Layout';
import API from '../../utils/api';
import moment from 'moment';
import { pdfTemplate } from '../../utils/pdfTemplate';
import { downloadInvoiceAsJpg } from '../../utils/downloadInvoice';

const SalesRepSalesHistory = () => {
  const navigate = useNavigate();
  const [sales, setSales] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const toast = useToast();

  const fetchHistory = async () => {
    try {
      const { data } = await API.get('/branch-sales'); // Backend filters for current sales Rep
      setSales(data.sales || []);
      setLoading(false);
    } catch (error) {
      toast({ title: "Error loading history", status: "error" });
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const handlePrint = (sale) => {
    const billData = {
      billNo: sale.invoiceId,
      clientName: sale.customerName,
      clientPhone: sale.customerPhone,
      items: sale.items,
      subTotal: sale.taxableAmount,
      totalTax: sale.gstAmount,
      taxPercentage: sale.gstRate,
      totalAmount: sale.totalAmount,
      isGstEnabled: sale.billingType === 'With GST',
      createdAt: sale.createdAt
    };
    const html = pdfTemplate(billData);
    const printWindow = window.open('', '_blank');
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.focus();
      printWindow.print();
    };
  };

  const handleDownloadInvoice = async (sale) => {
    const billData = {
      billNo: sale.invoiceId,
      clientName: sale.customerName,
      clientPhone: sale.customerPhone,
      items: sale.items,
      subTotal: sale.taxableAmount,
      totalTax: sale.gstAmount,
      taxPercentage: sale.gstRate,
      totalAmount: sale.totalAmount,
      isGstEnabled: sale.billingType === 'With GST',
      createdAt: sale.createdAt
    };
    
    const html = pdfTemplate(billData);
    toast({ title: "Generating JPG...", status: "info", duration: 2000 });
    try {
      await downloadInvoiceAsJpg(html, `Invoice_${sale.invoiceId}.jpg`);
    } catch (error) {
      toast({ title: "Failed to download", status: "error" });
    }
  };

  const filteredSales = sales.filter(s => 
    s.customerName?.toLowerCase().includes(searchTerm.toLowerCase()) || 
    s.invoiceId?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) {
    return <Layout><Flex justify="center" align="center" h="70vh"><Spinner size="xl" color="brand.500" /></Flex></Layout>;
  }

  return (
    <Layout>
      <Box p={6}>
        <Flex justify="space-between" align="center" mb={10}>
          <Box>
            <HStack spacing="3" mb="2">
               <Box p="2" bg="brand.50" color="brand.500" borderRadius="lg"><Receipt size={22}/></Box>
               <Heading size="lg" color="secondary" fontWeight="900" letterSpacing="-1px">My Super Stocklist Records</Heading>
            </HStack>
            <Text color="gray.500" fontWeight="500">History of all bills generated by you</Text>
          </Box>
          <HStack spacing="3">
             <Button leftIcon={<TrendingUp size={18} />} variant="outline" borderRadius="xl" onClick={() => navigate('/sales/dashboard')}>Performance</Button>
          </HStack>
        </Flex>

        <Box className="premium-card" overflow="hidden">
          <Box p="6" borderBottom="1px solid" borderColor="gray.50">
             <InputGroup maxW="400px" size="sm">
                <InputLeftElement><Search size={16} color="gray" /></InputLeftElement>
                <Input placeholder="Search invoice or customer..." borderRadius="lg" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} />
             </InputGroup>
          </Box>
          <Table variant="simple">
            <Thead bg="gray.50/50">
              <Tr>
                <Th py="5">Invoice ID</Th>
                <Th py="5">Customer</Th>
                <Th py="5">Products Sold</Th>
                <Th py="5">Grand Total</Th>
                <Th py="5">Date & Time</Th>
                <Th py="5" textAlign="right">Action</Th>
              </Tr>
            </Thead>
            <Tbody>
              {filteredSales.length > 0 ? filteredSales.map((sale) => (
                <Tr key={sale._id} _hover={{ bg: 'gray.50/30' }}>
                  <Td>
                    <Text fontWeight="800" color="brand.500" fontSize="xs">{sale.invoiceId}</Text>
                    <Badge variant="subtle" colorScheme={sale.billingType?.includes('GST') ? 'green' : 'orange'} fontSize="8px" borderRadius="full" px="2">{sale.billingType}</Badge>
                  </Td>
                  <Td>
                    <VStack align="start" spacing="0">
                       <Text fontWeight="800" fontSize="xs" color="secondary">{sale.customerName}</Text>
                       <Text fontSize="10px" color="gray.400">{sale.customerPhone}</Text>
                    </VStack>
                  </Td>
                  <Td>
                    <Text fontSize="xs" fontWeight="600" color="gray.600" noOfLines={1} maxW="250px">{sale.products}</Text>
                    <Text fontSize="9px" fontWeight="800" color="blue.500">{sale.totalQty} Units Sold</Text>
                  </Td>
                  <Td><Text fontWeight="900" color="secondary" fontSize="sm">₹{sale.totalAmount?.toLocaleString()}</Text></Td>
                  <Td>
                    <Text fontWeight="700" fontSize="xs">{moment(sale.createdAt).format('DD MMM, YYYY')}</Text>
                    <Text fontSize="10px" color="gray.400">{sale.time}</Text>
                  </Td>
                  <Td textAlign="right">
                    <HStack justify="flex-end" spacing="2">
                       <IconButton aria-label="Print" icon={<Printer size={16} />} size="sm" variant="ghost" onClick={() => handlePrint(sale)} />
                       <IconButton aria-label="Download" icon={<Download size={16} />} size="sm" variant="ghost" onClick={() => handleDownloadInvoice(sale)} />
                    </HStack>
                  </Td>
                </Tr>
              )) : (
                <Tr>
                  <Td colSpan="6" textAlign="center" py="10" color="gray.400">
                    <VStack spacing="2">
                      <ShoppingBag size={40} opacity={0.2} />
                      <Text fontWeight="600">No Super Stocklist records found</Text>
                      <Text fontSize="xs">Aapki sari Super Stocklist history yaha dikhayi degi.</Text>
                    </VStack>
                  </Td>
                </Tr>
              )}
            </Tbody>
          </Table>
        </Box>
      </Box>
    </Layout>
  );
};

export default SalesRepSalesHistory;


